### ISSUE TITLE
How to run demo?

### ISSUE THREAD

**Issue by bradparks** [Rich-Harris/ramjet#12]
Hey! I don't see any docs on how to run the demo... I tried running a local webserver and serving it, and that didn't work. Then I noticed there was a gooblefile there, so I installed gobble and tried running gobble, and that failed after installing a bunch of stuff with the following:

```
$ gobble
gobble: server listening on port 4567
gobble: livereload server running
gobble: 03-merge done in 84ms
%cRactive.js %c0.7.3 %cin debug mode, %cmore... color: rgb(114, 157, 52); font-weight: normal; color: rgb(85, 85, 85); font-weight: normal; color: rgb(85, 85, 85); font-weight: normal; color: rgb(82, 140, 224); font-weight: normal; text-decoration: underline;
You're running Ractive 0.7.3 in debug mode - messages will be printed to the console to help you fix problems and optimise your application.

To disable debug mode, add this line at the start of your app:
  Ractive.DEBUG = false;

To disable debug mode when your app is minified, add this snippet:
  Ractive.DEBUG = /unminified/.test(function(){/*unminified*/});

Get help and support:
  http://docs.ractivejs.org
  http://stackoverflow.com/questions/tagged/ractivejs
  http://groups.google.com/forum/#!forum/ractive-js
  http://twitter.com/ractivejs

Found a bug? Raise an issue:
  https://github.com/ractivejs/ractive/issues


%cRactive.js: %cInline partial comments are deprecated.
Use this...
  {{#partial const}} ... {{/partial}}

...instead of this:
  <!-- {{>const}} --> ... <!-- {{/const}} -->' color: rgb(114, 157, 52); color: rgb(85, 85, 85);
gobble: 04-ractive done in 226ms
gobble: 05-babel done in 2602ms
gobble: 06-esperantoBundle done in 341ms
gobble: 07-derequire done in 332ms
∙∙∙∙∙∙◦ 08-browserify running...
gobble: 08-browserify transformation failed

input:  /Users/bparks/gitrepos/ramjet_morph_dom_elements/.gobble/07
Error: Cannot find module 'ractive' from '/Users/bparks/gitrepos/ramjet_morph_dom_elements/.gobble/07-derequire/1'
    at /Users/bparks/gitrepos/ramjet_morph_dom_elements/node_modules/gobble-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/Users/bparks/gitrepos/ramjet_morph_dom_elements/node_modules/gobble-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/bparks/gitrepos/ramjet_morph_dom_elements/node_modules/gobble-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/bparks/gitrepos/ramjet_morph_dom_elements/node_modules/gobble-browserify/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/b
```

**Comment by Rich-Harris** [comment]
hmm, that's odd, it should build & serve the demo when you run `gobble` (or `npm start`, which does the same thing but without using any global packages). Just to eliminate the possibility of a corrupted node_modules folder, could you try...

```
$ cd /Users/bparks/gitrepos/ramjet_morph_dom_elements
$ rm -rf node_modules
$ npm i
$ npm start
```

...and see what happens?

**Comment by bradparks** [comment]
hmmm.... not sure what the difference was, but that did the trick... thanks!
